language: python

sudo: required

services:
  - docker

notifications:
  email:
    recipients:
      - raffaello@rnext.it
    on_success: change #[always|never|change] # default: change
    on_failure: always #[always|never|change] # default: always

jobs:
  include:
    - stage: Build and integration tests
      env: step=build_and_test
      script:
      - docker info
      - VERSION="$TRAVIS_BRANCH" make ci
    - env: step=build_and_test_random_user
      script:
      - docker info
      - USE_RANDOM_USER_ID=true VERSION="$TRAVIS_BRANCH" make ci
    - stage: Release
      if: type != pull_request AND tag IS present
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - VERSION="${TRAVIS_TAG}" make build
      - VERSION="${TRAVIS_TAG}" make release
      - VERSION="${TRAVIS_TAG}" make tag_latest
      - VERSION="${TRAVIS_TAG}" make release_latest
